### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'simplemango'!

### ISSUE THREAD

**Issue by pavog** [anviaan/SimpleMango#1]
Cool mod, unfortunately it does not work for me.

When I start my fresh new server (Fabric 1.18.2, Loader 0.14.5), I get the following error:

```
[12:46:08] [main/ERROR]: Failed to start the minecraft server
--
43 | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'simplemango'!
44 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.5.jar:?]
45 | at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.5.jar:?]
46 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.5.jar:?]
47 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.5.jar:?]
48 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.5.jar:?]
49 | at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
50 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.5.jar:?]
51 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.5.jar:?]
52 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.5.jar:?]
53 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.5.jar:?]
54 | Caused by: java.lang.NoSuchMethodError: 'net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings.breakByHand(boolean)'
55 | at net.anvian.simplemango.block.ModBlocks.<clinit>(ModBlocks.java:20) ~[SimpleMango-1.18.x-1.1.2.jar:?]
56 | at net.anvian.simplemango.world.features.ModConfiguredFeatures.<clinit>(ModConfiguredFeatures.java:19) ~[SimpleMango-1.18.x-1.1.2.jar:?]
57 | at net.anvian.simplemango.MangoMod.onInitialize(MangoMod.java:23) ~[SimpleMango-1.18.x-1.1.2.jar:?]
58 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.5.jar:?]
59 | ... 7 more
```

Full log:
https://mclo.gs/2nUvBOs

**Comment by anviaan** [comment]
I have tried and in the version of my mod for 1.18.2 it worked correctly, and I have tried with the version 1.18.x of the mod giving me the error that you sent, the solution is that you have to download the correct version according to your server. [LINK](https://www.curseforge.com/minecraft/mc-mods/simple-mango/files/3720629)
